### ISSUE TITLE
New resource tree change - issues / todo

### ISSUE THREAD

**Issue by polygoned** [polygoned/RadialGM#2]
~ Find full details for the new system at the bottom

Todo:
- [x] Add in the context the ability to change the folder's TypeCase
- [x] Clear persistent index list in 'Clear All Group Types'
- [ ] Perhaps show some sort of indication what TypeCase each folder is? A custom folder icon for each resource probably.
- [ ] Perhaps add a custom priority sorting in the context menu somehow. At the moment if you have more than 1 folder which has the same TypeCase it default creates a new resource in the first created folder (usually the default one presumably).
- [ ] Loaded GM files etc. should iterate through all the sub-folders to assign TypeCase to them.
- [ ] Perhaps add further functionality for people to create their own resource types inside RadialGM?
- [ ] Add in MainWindow::nodeResource.remove(index); when folder deleted. 
Note: Have the main window call this in a slot which it connects to the tree model removed signal. That way the tree model doesn't have to know anything about the main window and we can use it in other ways. Here's the signal: https://doc.qt.io/qt-5/qabstractitemmodel.html#rowsRemoved

----
Each folder has an assigned resource TypeCase to it. At game load it is automatically assigned based on the folder name. When you create a sub-folder it's TypeCase is automatically assigned to it's parent's. So if you create another shaders sub-folder inside the Shaders it will be assigned to kShader, even if you move it outside of the Shaders node (folders created outside the standard folders are assigned no TypeCase).

When you create a new resource it automatically goes into the first assigned node of the corresponding TypeCase (which will usually be the default folders created at game load). But if the current index is set on a folder which has a correct corresponding TypeCase it will be allowed to be created in that folder. So in the case of your new shaders folder you just have to select it (or select a resource inside it) then when a new shader is created it will be put inside that one instead.

You could also allow the TypeCase for a folder to be changed via the context menu, also note that with .gm file loading the sub-folders should also be assigned a TypeCase based on the parent node.

You could even set a preference scale in the context menu.  So your newly created shader folder could be set to the default shader node rather than the normal one.

**Comment by polygoned** [comment]
Deleting node now removes it from the map.
